#!/usr/bin/env python

import click
import os
import toml
import sys
import requests
from requests.auth import HTTPBasicAuth

class Clira(object):
    def __init__(self):
        try:
            clirarc_path = os.path.join(os.environ['HOME'], '.clirarc')
            print clirarc_path
            with open(clirarc_path) as clirarc:
                config = toml.loads(clirarc.read())

                self.auth = HTTPBasicAuth(
                    config['username'],
                    config['password'])

                self.jira_base_url = config['jira-instance-url']

        except IOError:
            print 'You need to first create a .clirarc file in your home directory'
            sys.exit(1)

        self.cli.add_command(self.show_config, name='show-config')

    @click.group()
    def cli(self):
        pass

    @click.command()
    def show_config(self):
        for key, value in self.config.items():
            print key, value

    @click.command()
    def list_projects(self):
        requests.get(self.jira_base_url, auth=self.auth)


if __name__ == '__main__':
    Clira().cli()

